version: '3.8'
services:
  cobra:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - AWS_ACCESS_KEY_ID=dummy
    command: python cobra-service.py
    volumes:
      - ./:/app

  lex-forensica:
    image: node:20-alpine
    ports:
      - "3000:3000"
    depends_on:
      - cobra
    environment:
      - COBRA_API=http://cobra:5000
    volumes:
      - ./vía:/app
    working_dir: /app